insert into ITEM (item_id, item_name, price) values (1, 'Turkey - Breast, Double', '$5.50');
insert into ITEM (item_id, item_name, price) values (2, 'Stock - Chicken, White', '$96.29');
insert into ITEM (item_id, item_name, price) values (3, 'Cheese - Cottage Cheese', '$37.38');
insert into ITEM (item_id, item_name, price) values (4, 'Tart Shells - Sweet, 3', '$36.57');
insert into ITEM (item_id, item_name, price) values (5, 'Muskox - French Rack', '$15.07');
insert into ITEM (item_id, item_name, price) values (6, 'Chips - Doritos', '$50.21');
insert into ITEM (item_id, item_name, price) values (7, 'Veal - Leg', '$69.09');
insert into ITEM (item_id, item_name, price) values (8, 'Octopus - Baby, Cleaned', '$91.22');
insert into ITEM (item_id, item_name, price) values (9, 'Sword Pick Asst', '$53.39');
insert into ITEM (item_id, item_name, price) values (10, 'Snapple - Iced Tea Peach', '$33.28');
insert into ITEM (item_id, item_name, price) values (11, 'Lid Coffee Cup 8oz Blk', '$48.26');
insert into ITEM (item_id, item_name, price) values (12, 'Cheese - Camembert', '$10.97');
insert into ITEM (item_id, item_name, price) values (13, 'Filo Dough', '$21.99');
insert into ITEM (item_id, item_name, price) values (14, 'Wine - Winzer Krems Gruner', '$26.97');
insert into ITEM (item_id, item_name, price) values (15, 'Carbonated Water - Wildberry', '$99.07');
insert into ITEM (item_id, item_name, price) values (16, 'Schnappes - Peach, Walkers', '$55.27');
insert into ITEM (item_id, item_name, price) values (17, 'Tea - Decaf 1 Cup', '$69.65');
insert into ITEM (item_id, item_name, price) values (18, 'Huck White Towels', '$33.05');
insert into ITEM (item_id, item_name, price) values (19, 'Pepper - Chilli Seeds Mild', '$23.84');
insert into ITEM (item_id, item_name, price) values (20, 'Garbag Bags - Black', '$58.23');
insert into ITEM (item_id, item_name, price) values (21, 'Ham - Virginia', '$86.04');
insert into ITEM (item_id, item_name, price) values (22, 'Icecream Bar - Del Monte', '$31.02');
insert into ITEM (item_id, item_name, price) values (23, 'Bar Energy Chocchip', '$28.91');
insert into ITEM (item_id, item_name, price) values (24, 'Bay Leaf Ground', '$12.57');
insert into ITEM (item_id, item_name, price) values (25, 'Calvados - Boulard', '$30.31');
insert into ITEM (item_id, item_name, price) values (26, 'Squid - Tubes / Tenticles 10/20', '$74.17');
insert into ITEM (item_id, item_name, price) values (27, 'Pepper - Cayenne', '$50.73');
insert into ITEM (item_id, item_name, price) values (28, 'Beef - Tenderlion, Center Cut', '$54.77');
insert into ITEM (item_id, item_name, price) values (29, 'Cake - Night And Day Choclate', '$68.56');
insert into ITEM (item_id, item_name, price) values (30, 'Squash - Pepper', '$10.77');
insert into ITEM (item_id, item_name, price) values (31, 'Sultanas', '$63.63');
insert into ITEM (item_id, item_name, price) values (32, 'Chocolate - Mi - Amere Semi', '$38.78');
insert into ITEM (item_id, item_name, price) values (33, 'Juice - Apple 284ml', '$61.42');
insert into ITEM (item_id, item_name, price) values (34, 'Bagel - Sesame Seed Presliced', '$75.52');
insert into ITEM (item_id, item_name, price) values (35, 'Soy Protein', '$55.84');
insert into ITEM (item_id, item_name, price) values (36, 'Versatainer Nc - 9388', '$52.54');
insert into ITEM (item_id, item_name, price) values (37, 'Orange - Tangerine', '$60.41');
insert into ITEM (item_id, item_name, price) values (38, 'Carrots - Jumbo', '$11.80');
insert into ITEM (item_id, item_name, price) values (39, 'Syrup - Monin - Granny Smith', '$47.83');
insert into ITEM (item_id, item_name, price) values (40, 'Tamarillo', '$67.77');
insert into ITEM (item_id, item_name, price) values (41, 'Beer - Sleemans Cream Ale', '$68.02');
insert into ITEM (item_id, item_name, price) values (42, 'Pasta - Gnocchi, Potato', '$39.67');
insert into ITEM (item_id, item_name, price) values (43, 'Pepper - Gypsy Pepper', '$19.79');
insert into ITEM (item_id, item_name, price) values (44, 'Sardines', '$83.14');
insert into ITEM (item_id, item_name, price) values (45, 'Apricots Fresh', '$43.20');
insert into ITEM (item_id, item_name, price) values (46, 'Beef - Inside Round', '$62.59');
insert into ITEM (item_id, item_name, price) values (47, 'Cookies - Englishbay Wht', '$96.11');
insert into ITEM (item_id, item_name, price) values (48, 'Pork - Liver', '$79.47');
insert into ITEM (item_id, item_name, price) values (49, '7up Diet, 355 Ml', '$23.22');
insert into ITEM (item_id, item_name, price) values (50, 'Miso Paste White', '$15.04');
insert into ITEM (item_id, item_name, price) values (51, 'Juice - V8 Splash', '$54.76');
insert into ITEM (item_id, item_name, price) values (52, 'Plate - Foam, Bread And Butter', '$73.93');
insert into ITEM (item_id, item_name, price) values (53, 'Lemon Pepper', '$41.40');
insert into ITEM (item_id, item_name, price) values (54, 'Cheese - Brie Roitelet', '$64.94');
insert into ITEM (item_id, item_name, price) values (55, 'Cabbage - Red', '$98.77');
insert into ITEM (item_id, item_name, price) values (56, 'Muffin Batt - Carrot Spice', '$21.75');
insert into ITEM (item_id, item_name, price) values (57, 'Plums - Red', '$21.91');
insert into ITEM (item_id, item_name, price) values (58, 'Chicken - White Meat With Tender', '$81.37');
insert into ITEM (item_id, item_name, price) values (59, 'Pasta - Fettuccine, Dry', '$87.10');
insert into ITEM (item_id, item_name, price) values (60, 'Wine - Cousino Macul Antiguas', '$38.04');
insert into ITEM (item_id, item_name, price) values (61, 'Stock - Chicken, White', '$67.48');
insert into ITEM (item_id, item_name, price) values (62, 'Cheese - Parmigiano Reggiano', '$59.05');
insert into ITEM (item_id, item_name, price) values (63, 'Schnappes Peppermint - Walker', '$81.67');
insert into ITEM (item_id, item_name, price) values (64, 'Cut Wakame - Hanawakaba', '$75.90');
insert into ITEM (item_id, item_name, price) values (65, 'Apple - Northern Spy', '$7.34');
insert into ITEM (item_id, item_name, price) values (66, 'Anchovy In Oil', '$7.09');
insert into ITEM (item_id, item_name, price) values (67, 'Scallops - In Shell', '$36.35');
insert into ITEM (item_id, item_name, price) values (68, 'Asparagus - Green, Fresh', '$91.00');
insert into ITEM (item_id, item_name, price) values (69, 'Chicken - White Meat, No Tender', '$89.31');
insert into ITEM (item_id, item_name, price) values (70, 'Appetizer - Veg Assortment', '$58.64');
insert into ITEM (item_id, item_name, price) values (71, 'Alize Sunset', '$21.11');
insert into ITEM (item_id, item_name, price) values (72, 'Pork - Butt, Boneless', '$16.79');
insert into ITEM (item_id, item_name, price) values (73, 'Noodles - Steamed Chow Mein', '$99.54');
insert into ITEM (item_id, item_name, price) values (74, 'Sugar - Brown', '$32.34');
insert into ITEM (item_id, item_name, price) values (75, 'Edible Flower - Mixed', '$51.35');
insert into ITEM (item_id, item_name, price) values (76, 'Lamb Leg - Bone - In Nz', '$81.82');
insert into ITEM (item_id, item_name, price) values (77, 'Filo Dough', '$33.87');
insert into ITEM (item_id, item_name, price) values (78, 'The Pop Shoppe - Lime Rickey', '$75.24');
insert into ITEM (item_id, item_name, price) values (79, 'Muffin Batt - Blueberry Passion', '$59.91');
insert into ITEM (item_id, item_name, price) values (80, 'Pomegranates', '$87.07');
insert into ITEM (item_id, item_name, price) values (81, 'Cucumber - Pickling Ontario', '$90.41');
insert into ITEM (item_id, item_name, price) values (82, 'Pail - 15l White, With Handle', '$93.94');
insert into ITEM (item_id, item_name, price) values (83, 'Cucumber - English', '$88.24');
insert into ITEM (item_id, item_name, price) values (84, 'Chicken - Soup Base', '$76.95');
insert into ITEM (item_id, item_name, price) values (85, 'Onions - Red', '$49.16');
insert into ITEM (item_id, item_name, price) values (86, 'Clams - Canned', '$48.74');
insert into ITEM (item_id, item_name, price) values (87, 'External Supplier', '$39.81');
insert into ITEM (item_id, item_name, price) values (88, 'Pasta - Angel Hair', '$45.71');
insert into ITEM (item_id, item_name, price) values (89, 'Grenadine', '$8.94');
insert into ITEM (item_id, item_name, price) values (90, 'Yokaline', '$12.83');
insert into ITEM (item_id, item_name, price) values (91, 'Pastry - French Mini Assorted', '$33.43');
insert into ITEM (item_id, item_name, price) values (92, 'Cheese - Brie', '$69.27');
insert into ITEM (item_id, item_name, price) values (93, 'Bread - Multigrain Oval', '$83.19');
insert into ITEM (item_id, item_name, price) values (94, 'Pail - 15l White, With Handle', '$78.49');
insert into ITEM (item_id, item_name, price) values (95, 'Juice - Pineapple, 341 Ml', '$79.72');
insert into ITEM (item_id, item_name, price) values (96, 'Pasta - Linguini, Dry', '$45.61');
insert into ITEM (item_id, item_name, price) values (97, 'Sterno - Chafing Dish Fuel', '$71.74');
insert into ITEM (item_id, item_name, price) values (98, 'The Pop Shoppe - Cream Soda', '$15.64');
insert into ITEM (item_id, item_name, price) values (99, 'Shrimp - Baby, Cold Water', '$11.04');
insert into ITEM (item_id, item_name, price) values (100, 'Lobak', '$71.58');
